app:
  name: easy-swap-nft-market
  port: 8088

mysql:
  dsn: "root:rootpasswd@tcp(127.0.0.1:3307)/nftMarket?charset=utf8mb4&parseTime=True&loc=Local"

chain:
  rpc: "https://eth-sepolia.g.alchemy.com/v2/qYzNDoA70IIpPivi7CKE3"
  safe_block: 6
  scan_interval: 3

contract:
  nft: "0xC25E680C1480533FE69eAc43A8cF98c0a339eEaf"
  market: "0xcEE5AA84032D4a53a0F9d2c33F36701c3eAD5895"